questions = [
    {'question': 'What does len("hello") return?', 'answer': 'b', 'a': '4', 'b': '5'},
    {'question': 'What data type does input() always return?', 'answer': 'b', 'a': 'int', 'b': 'str'},
    {'question': 'How do you add an item to a list?', 'answer': 'a', 'a': 'list.append()', 'b': 'list.add()'},
    {'question': 'What does // do in Python?', 'answer': 'b', 'a': 'Division', 'b': 'Floor division'},
    {'question': 'What keyword defines a function?', 'answer': 'a', 'a': 'def', 'b': 'func'},
    {'question': 'What does % return?', 'answer': 'b', 'a': 'Division result', 'b': 'Remainder'},
    {'question': 'How do you convert "5" to an integer?', 'answer': 'a', 'a': 'int("5")', 'b': 'str("5")'},
    {'question': 'What does return do in a function?', 'answer': 'b', 'a': 'Prints the value', 'b': 'Sends value back to caller'},
    {'question': 'Which loop is used to iterate over a list?', 'answer': 'a', 'a': 'for', 'b': 'repeat'},
    {'question': 'What does bool(0) return?', 'answer': 'b', 'a': 'True', 'b': 'False'},
    {'question': 'How do you access a dictionary value?', 'answer': 'a', 'a': 'dict["key"]', 'b': 'dict.get key'},
    {'question': 'What does .lower() do?', 'answer': 'b', 'a': 'Removes spaces', 'b': 'Converts to lowercase'},
    {'question': 'What is the result of 2 ** 3?', 'answer': 'a', 'a': '8', 'b': '6'},
    {'question': 'Which keyword stops a loop immediately?', 'answer': 'b', 'a': 'stop', 'b': 'break'},
    {'question': 'What does range(5) produce?', 'answer': 'a', 'a': '0,1,2,3,4', 'b': '1,2,3,4,5'},
    {'question': 'How do you check the type of a variable?', 'answer': 'b', 'a': 'typeof(x)', 'b': 'type(x)'},
    {'question': 'What does .strip() do?', 'answer': 'a', 'a': 'Removes whitespace', 'b': 'Removes letters'},
    {'question': 'What is a correct way to create a list?', 'answer': 'b', 'a': 'list = (1, 2, 3)', 'b': 'list = [1, 2, 3]'},
    {'question': 'What does "not True" return?', 'answer': 'a', 'a': 'False', 'b': 'True'},
    {'question': 'How do you get the last item of a list?', 'answer': 'b', 'a': 'list[0]', 'b': 'list[-1]'},
    {'question': 'What does .split() do?', 'answer': 'a', 'a': 'Splits string into list', 'b': 'Splits list into string'},
    {'question': 'What keyword skips to next iteration?', 'answer': 'b', 'a': 'skip', 'b': 'continue'},
    {'question': 'What is the result of "3" + "3"?', 'answer': 'a', 'a': '"33"', 'b': '6'},
    {'question': 'How do you check if a key exists in a dict?', 'answer': 'b', 'a': 'key in dict.values()', 'b': 'key in dict'},
    {'question': 'What does randint(1, 10) include?', 'answer': 'a', 'a': 'Both 1 and 10', 'b': 'Only 1'},
]